apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-todoapp
spec:
  rules:
    - host: "todoapp.dev"
      http:
        paths:
          - pathType: Prefix
            path: "/api/auth"
            backend:
              service:
                name: todoapp-auth-srv
                port:
                  number: 8080
          - pathType: Prefix
            path: "/api/tasks"
            backend:
              service:
                name: todoapp-core-srv
                port:
                  number: 3000
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: todoapp-web-srv
                port:
                  number: 8080
