apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - auth
  - core
  - web
  - mysql
  - mongo

labels:
  - pairs:
      app.kubernetes.io/managed-by: kustomize
      app.kubernetes.io/part-of: todoapp
    includeSelectors: true

commonAnnotations:
  contact: devops@todoapp.com
