apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev

labels:
  - includeSelectors: true
    pairs:
      env: dev

images:
  - name: dalthonmh/todoapp-web
    newTag: "dev"

resources:
  - namespace.yaml
  - ../../base/
